site_name: Documentation++
theme:
  name: material
  palette:
    scheme: slate
    primary: red
  features:
    - content.code.annotate
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details